#!/bin/sh
set -x
mkdir -p cert
cd cert

# CA key
openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve:P-256 -out ca.key
chmod 600 ca.key

# CA cert
openssl req -key ca.key -new -x509 -days 365 -addext keyUsage=critical,keyCertSign,cRLSign -subj "/CN=<Example CA>" -out ca.cert

# Server key
openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve:P-256 -out server.key

# Server csr
openssl req -key server.key -config ../server.conf -new -out server.csr

# Server cert
openssl x509 -req -in server.csr -CA ca.cert -CAkey ca.key -CAcreateserial -days 365 -extfile ../openssl.conf -extensions server-cert -out server.cert

# Client key
openssl genpkey -algorithm ec -pkeyopt ec_paramgen_curve:P-256 -out client.key

# Client csr
openssl req -key client.key -config ../client.conf -new -out client.csr

# Client cert
openssl x509 -req -in client.csr -CA ca.cert -CAkey ca.key -CAcreateserial -days 365 -extfile ../openssl.conf -extensions client-cert -out client.cert
